apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: mlops-recommendation
type: Opaque
data:
  SECRET_KEY: <base64-encoded-secret>
  DB_PASSWORD: <base64-encoded-password>
  AWS_ACCESS_KEY_ID: <base64-encoded-aws-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-aws-secret>
  SONAR_TOKEN: <base64-encoded-sonar-token>