global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-recommendation'
    static_configs:
      - targets: ['fastapi-recommendation:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5001']

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093